
"""
Project Euler problem solutions using Python

by

Charanraj Thimmisetty
charanrajt@gmail.com

Q:

Each new term in the Fibonacci sequence is generated by adding the previous
 two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose 
values do not exceed four million, find the sum of the even-valued terms.
"""
#Solution one
#Use recurssive implimenation of the Fibonacci
def rec_fib(n):
    if n<2:
        return (n,1)
    elif n>0:
         a,b=rec_fib(n-1)
         return (a+b,a)
         
print rec_fib(6)[0]         


import time as time
t1=time.time()
sum=0;

n=2;
current_fib=rec_fib(n)[0];

while (current_fib<4e6):
    if current_fib%2==0:
        sum=sum+current_fib
    n=n+1;
    current_fib=rec_fib(n)[0]
print 'Ans is:', sum   

t2=time.time()
print t2-t1
#Compute Fib on the fly
new_fib=2;
n=2;
sum1=0;
a=2
b=1
while (new_fib<4e6):
    if new_fib%2==0:
        sum1=sum1+new_fib
    a=a+b;
    b=a-b;
    new_fib=a;
   
    
print 'Ans is:', sum1   

print time.time()-t2
